remote_theme: daattali/beautiful-jekyll

title: Abby Notes
plugins:
  - jekyll-remote-theme

navbar-col: "#FFC0CB"
navbar-text-col: "#4A0033"
navbar-children-col: "#F5F5F5"
hover-col: "#FF69B4"
page-col: "#FFF5F8"
link-col: "#C2185B"
footer-col: "#FBE4EC"
footer-text-col: "#6b7280"
footer-link-col: "#C2185B"

defaults:
  - scope:
      path: ""
    values:
      render_with_liquid: false
      head-extra:
        - my-head-extra.html